[2023-08-10T20:10:45.504+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 7_da_temps.hit_open_meteo manual__2023-08-10T20:10:43.952664+00:00 [queued]>
[2023-08-10T20:10:45.508+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 7_da_temps.hit_open_meteo manual__2023-08-10T20:10:43.952664+00:00 [queued]>
[2023-08-10T20:10:45.508+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-10T20:10:45.513+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): hit_open_meteo> on 2023-08-10 20:10:43.952664+00:00
[2023-08-10T20:10:45.517+0000] {standard_task_runner.py:57} INFO - Started process 54 to run task
[2023-08-10T20:10:45.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '7_da_temps', 'hit_open_meteo', 'manual__2023-08-10T20:10:43.952664+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/7_da_weather/7_da_temps.py', '--cfg-path', '/tmp/tmpycaozmaj']
[2023-08-10T20:10:45.523+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask hit_open_meteo
[2023-08-10T20:10:45.555+0000] {task_command.py:410} INFO - Running <TaskInstance: 7_da_temps.hit_open_meteo manual__2023-08-10T20:10:43.952664+00:00 [running]> on host 199121aa9c86
[2023-08-10T20:10:45.792+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='scott' AIRFLOW_CTX_DAG_ID='7_da_temps' AIRFLOW_CTX_TASK_ID='hit_open_meteo' AIRFLOW_CTX_EXECUTION_DATE='2023-08-10T20:10:43.952664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-10T20:10:43.952664+00:00'
[2023-08-10T20:10:45.793+0000] {logging_mixin.py:150} INFO - ['/home/***/.local/bin', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/home/***/.local/lib/python3.11/site-packages', '/usr/local/lib/python3.11/site-packages', '/opt/***/dags', '/opt/***/config', '/opt/***/plugins', '/opt/***']
[2023-08-10T20:10:45.794+0000] {logging_mixin.py:150} INFO - /opt/***/utils
[2023-08-10T20:10:45.794+0000] {logging_mixin.py:150} INFO - ['__pycache__', 'meteo_wrapper.py']
[2023-08-10T20:10:45.795+0000] {logging_mixin.py:150} INFO - Hello world!
[2023-08-10T20:10:45.797+0000] {logging_mixin.py:150} INFO - 34.09780533236823
[2023-08-10T20:10:46.151+0000] {logging_mixin.py:150} INFO - {"reason":"Value of type 'Float' required for key 'longitude'.","error":true}
[2023-08-10T20:10:46.157+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-10T20:10:46.175+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=7_da_temps, task_id=hit_open_meteo, execution_date=20230810T201043, start_date=20230810T201045, end_date=20230810T201046
[2023-08-10T20:10:46.239+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-10T20:10:46.254+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
